### ISSUE TITLE
Graph line disappears after four 1's

### ISSUE THREAD

**Issue by pengowray** [open-spaced-repetition/anki_fsrs_visualizer#1]
I think I found a bug?

If you graph a set of reviews which start with four 1's, the graph line just disappears and no amount of 4's will bring it back, e.g. `1111444444444` :

![image](https://github.com/xiety/anki_fsrs_visualizer/assets/800133/6f317352-1ef4-410c-8a84-f893e97c1413)

**Fig 1: `1111444444444`: all other settings are defaults, but I've zoomed in the graph. Shows up to review #4 and then the graph disappears and never recovers.**

If you delete a 1 it works as expected:

![image](https://github.com/xiety/anki_fsrs_visualizer/assets/800133/5ed3c814-2aec-4115-8b07-278d717e5cb7)

**Fig 2: `1114444444444` works as expected**

Another example which shows this problem:

41111114444444444

(also works as expected once you delete a 1)

I suspect you need some sort of minimum review interval or some way to stop some variable reaching 0 or going negative.

**Comment by xiety** [comment]
I've added a clamp of a difficulty from 0% to 100% and it fixes this problem
`- ..-`
