### ISSUE TITLE
Invitation from open spaced repetition

### ISSUE THREAD

**Issue by L-M-Sherlock** [open-spaced-repetition/anki_fsrs_visualizer#2]
I want to invite you to join @open-spaced-repetition. Would you like to join it and move this repository to the organization? I hope you can continue to maintain it in the organization.

**Comment by xiety** [comment]
Thank you for the invitation! I would be happy to join the organization and move this repository there.

**Comment by xiety** [comment]
@L-M-Sherlock The link in the "About" section of this repository incorrectly points to the previous location, and I do not have permission to change it. There was a check box "Use your GitHub Pages website". It’s strange that it didn’t update itself during the transfer. Can you please fix it?

**Comment by L-M-Sherlock** [comment]
I have set you as the admin of this repo just now. You can give it a try.
