### ISSUE TITLE
Help, cannot figure out how to customize Easy rating

### ISSUE THREAD

**Issue by SnowdayAurelion** [open-spaced-repetition/anki_fsrs_visualizer#5]
I'm trying to replicate the spacing intervals on the [Anki FSRS](https://open-spaced-repetition.github.io/anki_fsrs_visualizer/) with [py fsrs](https://pypi.org/project/fsrs/) and cannot figure this out. I made a simple Python code that loops through a list of ratings and automatically sets the next review date as the recommended due date.

```python
import fsrs
import datetime as dt

f = fsrs.FSRS()
card = fsrs.Card()
date = dt.datetime.now()

ratings = [3, 3, 3]

for rating in ratings:
    card_schedules = f.repeat(card, date)
    card = card_schedules[rating].card

    print(f"Lapse: {card.lapses}\nRating: {rating}\nStability: {card.stability}\nDate reviewed: {date}\nDays between: {card.due - date}\nDue Date: {card.due}\n\n\n")

    date = card.due  # next date reviewed is due date
```

I've been working on trying to replicate the Anki FSRS into Python for the past 3-4 days. Today I realized the Anki FSRS Visualizer shows reviews, so it ignores the initial dates. So I edited the `fsrs.py` code to have my own initial dates.

```python
if card.state == State.New:
    self.init_ds(s)

    s.again.due = now + timedelta(minutes=1)
    s.hard.due = now + timedelta(hours=12)
    s.good.due = now + timedelta(days=1)
    # easy_interval = self.next_interval(s.easy.stability)
    # s.easy.scheduled_days = easy_interval
    s.easy.due = now + timedelta(days=2)
```

This works fine for `Good`.

```
Lapse: 0
Rating: 3
Stability: 7.0
Date reviewed: 2024-05-23 16:50:43.177066   
Days between: 1 day, 0:00:00
Due Date: 2024-05-24 16:50:43.177066        



Lapse: 0
Rating: 3
Stability: 7.0
Date reviewed: 2024-05-24 16:50:43.177066   
Days between: 7 days, 0:00:00 ⬅️
Due Date: 2024-05-31 16:50:43.177066        



Lapse: 0
Rating: 3
Stability: 18.200353648176815
Date reviewed: 2024-05-31 16:50:43.177066   
Days between: 18 days, 0:00:00 ⬅️
Due Date: 2024-06-18 16:50:43.177066
```

After initialization, the intervals match up.

![image](https://github.com/open-spaced-repetition/anki_fsrs_visualizer/assets/56422780/ccc9707e-dbc5-4e56-ab0a-3ed159d369d4)

This works fine for `Hard` (okay nvm looking at it now it does not).

```
Lapse: 0
Rating: 2
Stability: 3.0
Date reviewed: 2024-05-23 16:52:57.263225   
Days between: 12:00:00
Due Date: 2024-05-24 04:52:57.263225        



Lapse: 0
Rating: 2
Stability: 3.0
Date reviewed: 2024-05-24 04:52:57.263225   
Days between: 1 day, 0:00:00 ⬅️
Due Date: 2024-05-25 04:52:57.263225        



Lapse: 0
Rating: 2
Stability: 3.0
Date reviewed: 2024-05-25 04:52:57.263225   
Days between: 1 day, 0:00:00 ⬅️
Due Date: 2024-05-26 04:52:57.263225
```

![image](https://github.com/open-spaced-repetition/anki_fsrs_visualizer/assets/56422780/312b720a-a727-4cab-bfb4-fb38e23aff1e)

Then it breaks completely for `Easy`.

```
Lapse: 0
Rating: 4
Stability: 9.0
Date reviewed: 2024-05-23 16:55:42.639656   
Days between: 2 days, 0:00:00
Due Date: 2024-05-25 16:55:42.639656        



Lapse: 0
Rating: 4
Stability: 20.912799345272045
Date reviewed: 2024-05-25 16:55:42.639656   
Days between: 21 days, 0:00:00 ⬅️
Due Date: 2024-06-15 16:55:42.639656        



Lapse: 0
Rating: 4
Stability: 137.3074913295799
Date reviewed: 2024-06-15 16:55:42.639656   
Days between: 137 days, 0:00:00 ⬅️
Due Date: 2024-10-30 16:55:42.639656
```

![image](https://github.com/open-spaced-repetition/anki_fsrs_visualizer/assets/56422780/8cb1d8a8-8cc4-409a-b0ff-26b7cc46b136)

My main question is, what does the Anki FSRS represent initially? Because the input is called "Reviews." So I'm unsure how the Python FSRS deals with the initial `Rating`. That's by far the most confusing thing to me.

The other thing is, how is `Easy` being treated differently? Because the stability is duplicated for `Good`.

```
Lapse: 0
Rating: 3
Stability: 7.0 ⬅️
Date reviewed: 2024-05-23 16:55:36.644540   
Days between: 1 day, 0:00:00
Due Date: 2024-05-24 16:55:36.644540        



Lapse: 0
Rating: 4
Stability: 7.0⬅️
Date reviewed: 2024-05-24 16:55:36.644540   
Days between: 8 days, 0:00:00
Due Date: 2024-06-01 16:55:36.644540
```

But it is not for `Easy`.

```
Lapse: 0
Rating: 4
Stability: 9.0 ⬅️
Date reviewed: 2024-05-23 16:55:42.639656   
Days between: 2 days, 0:00:00
Due Date: 2024-05-25 16:55:42.639656        



Lapse: 0
Rating: 4
Stability: 20.912799345272045 ⬅️ (different)
Date reviewed: 2024-05-25 16:55:42.639656   
Days between: 21 days, 0:00:00
Due Date: 2024-06-15 16:55:42.639656        



Lapse: 0
Rating: 4
Stability: 137.3074913295799
Date reviewed: 2024-06-15 16:55:42.639656   
Days between: 137 days, 0:00:00
Due Date: 2024-10-30 16:55:42.639656
```

I would really like some help here, please. I've been trying to use this py FSRS for the past 3-4 days and cannot figure it out. Maybe another solution is to directly take the data from the Anki FSRS if possible. Maybe I can simulate the FSRS somehow.

Any help would be appreciated. I'm completely lost!

**Comment by xiety** [comment]
This repository ignores Learning card state. So, in `ts-fsrs` mode I had to replace the state and due date of the card with some simple calculations. You can see them here:

https://github.com/open-spaced-repetition/anki_fsrs_visualizer/blob/b4aca4fe02c16ca7166ee6b0ffc446fdd7090f82/src/tsFsrsCalculator.ts#L43-L45

But the Easy state doesn't use the Learning state, so I'm not really sure what you're looking for.

**Comment by SnowdayAurelion** [comment]
I believe it would have been more appropriate to create the issue in the py-fsrs GitHub as my problems are more related to there.

Regarding your post, you mention that `Easy` does not use the `Learning` state, but I'm confused because isn't it used here on line 43?
https://github.com/open-spaced-repetition/py-fsrs/blob/5d36ec32bcac350b489b78dd6c20b26a38582d09/src/fsrs/fsrs.py#L40-L43

Also, I'm unsure what `ts-fsrs` is, a quick explanation would be appreciated.

I'll be more precise with my previous questions, information on these would seriously help me out:
1. Does the FSRS Anki assume `New` state? When I look at the FSRS Anki, the input box to place repetitions is called "Reviews". I assume that means that if I were to input `234`, that `2` is in the `Learning` state and not `New`.
2. Does hard-coding the initial time intervals for `New` cards in `fsrs.py` break the algorithm or cause any inconsistencies between FSRS Anki and py-fsrs?
For example, before:
https://github.com/open-spaced-repetition/py-fsrs/blob/5d36ec32bcac350b489b78dd6c20b26a38582d09/src/fsrs/fsrs.py#L35-L39

after my custom intervals:
```python
s.hard.due = now + timedelta(hours=12)
s.good.due = now + timedelta(days=1)
# easy_interval = self.next_interval(s.easy.stability)
# s.easy.scheduled_days = easy_interval
s.easy.due = now + timedelta(days=2)
```
3. Is there any Python code you made that I can use that shows exactly how to replicate the results in Anki FSRS with py-fsrs? I'm not sure what else to do here because I feel I tried everything. I thought once I placed the parameters for `w` it would work but I seriously cannot seem to find how both Anki FSRS and py-fsrs relate.

Thank you so much for your help and information.

**Comment by xiety** [comment]
Here is the simple Python code that repeats the behavour of this repository:

```` Python
from datetime import datetime, timedelta, timezone

from fsrs import *

reviews = [[3, 3, 3, 3],
           [3, 3, 3, 2],
           [3, 3, 3, 1],
           [2, 3, 3, 3],
           [1, 3, 3, 3],
           [4, 3, 3, 1]]

for review in reviews:
    print(review)

    f = FSRS()
    f.p.w = (0.5701, 1.4436, 4.1386, 10.9355, 5.1443, 1.2006, 0.8627, 0.0362,
             1.6290, 0.1342, 1.0166, 2.1174, 0.0839, 0.3204, 1.4676, 0.2190, 2.8237)

    card = Card()
    card.due = datetime.now(timezone.utc)

    for grade in review:
        scheduling_cards = f.repeat(card, card.due)
        card = scheduling_cards[grade].card

        if (card.state != State.Review):
            card.state = State.Review
            interval = f.next_interval(card.stability)
            card.due = card.due + timedelta(days=interval)

        print(f"{card.stability:.2f}")
````

**Comment by SnowdayAurelion** [comment]
This is exactly what I wanted thank you! Only last detail though is how can we have this code be aware of the date reviewed. For example, if I were to not exactly review on the recommend due date, it should adjust the dates. Right now, the code purely exports the sequence of due dates as if I were to perfectly be on schedule. This is how I tried to adjust the code but seems to not change anything.
````python
def fsrs_card(reviews= None, dates = None):
    reviews = [2, 3, 3, 3] # testing
    date = datetime.now(timezone.utc)
    dates = [date, date+timedelta(days=1), date+timedelta(days=10),date+timedelta(days=50)] # testing

    f = FSRS()
    f.p.w = (0.4000, 0.5100, 1.0000, 2.0000, 1.0000, 0.9400, 0.8600, 0.0100, 1.3900, 0.1400, 0.9400, 2.1800, 0.0500, 0.3400, 1.2600, 0.2500, 1.5200)

    card = Card()
    card.due = dates[0] # initial date is first date reviewed

    reviews_dates = zip(reviews,dates) # review difficulty + date reviewed

    for grade, date in reviews_dates:
        scheduling_cards = f.repeat(card, card.due)
        card = scheduling_cards[grade].card

        if (card.state != State.Review):
            card.state = State.Review
            interval = f.next_interval(card.stability)
            card.due = date + timedelta(days=interval) # date actually reviewed + interval
            card.last_review = date # make card aware of actual date reviewed

        print(card.due)
        # print(f"{card.stability:.2f}")
        # intervals.append(card.stability)

    return card
````

Thank you so much so far! This should be the final cherry on the cake

**Comment by xiety** [comment]
You should pass real review date into the second parameter of `f.repeat` method.

**Comment by SnowdayAurelion** [comment]
I am happy to say everything works exactly how what I want. Thank you so much! The system I made using fsrs is a dream. Thank you!!
