### ISSUE TITLE
Update the visualizer to match the latest version of FSRS-5

### ISSUE THREAD

**Issue by Expertium** [open-spaced-repetition/anki_fsrs_visualizer#9]
https://github.com/open-spaced-repetition/fsrs-optimizer
I don't think that the current version of the visualizer is fully up-to-date

**Comment by xiety** [comment]
This repository uses version `4.4.2` of this library: https://github.com/open-spaced-repetition/ts-fsrs

And it is the latest version for today: https://github.com/open-spaced-repetition/ts-fsrs/releases

What exactly is not up to date? Can you give some example?

**Comment by Expertium** [comment]
https://huggingface.co/spaces/open-spaced-repetition/fsrs4anki_previewer
FSRS-5 parameters: 0.40255, 1.18385, 3.173, 15.69105, 7.1949, 0.5345, 1.4604, 0.0046, 1.54575, 0.1192, 1.01925, 1.9395, 0.11, 0.29605, 2.2698, 0.2315, 2.9898, 0.51655, 0.6621
Desired retention: 0.9
Ratings: 1,2,1,2
Output:
```
rating history: 1,2,1,2
interval history: 0.0d,1.0d,1.0d,1.0d,1.0d
factor history: 0.0,0.0,1.00,1.00,1.00
difficulty history: 0,7.2,7.6,8.4,8.6
```
7.2 is 69%, 7.6 is 73%, 8.4 is 82%, 8.6 is 84%.

Visualizer:
![image](https://github.com/user-attachments/assets/6926e734-aa47-450a-91ff-7d78accefeff)

The difficulty formula has recently been updated. Perhaps ts-FSRS hasn't been updated?

**Comment by xiety** [comment]
I found that `FSRS-Optimizer` added linear damping here: https://github.com/open-spaced-repetition/fsrs-optimizer/pull/143

It is already implemented in https://github.com/open-spaced-repetition/fsrs-rs/pull/239 and in https://github.com/open-spaced-repetition/fsrs4anki/pull/702

But neither [ts-fsrs](https://github.com/open-spaced-repetition/ts-fsrs/tree/main/src/fsrs/algorithm.ts#L170) nor [py-fsrs](https://github.com/open-spaced-repetition/py-fsrs/tree/main/src/fsrs/fsrs.py#L198) nor [rs-fsrs](https://github.com/open-spaced-repetition/rs-fsrs/tree/master/src/parameters.rs#L53) have added it yet.

So I will wait for https://github.com/open-spaced-repetition/ts-fsrs/pull/133 to catch up with it.

**Comment by ishiko732** [comment]
> Perhaps ts-FSRS hasn't been updated?

ts-fsrs has not yet approved the merge of linear damping. Please wait for the stable release of Anki.
